name: Build and Test on Windows

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        generator:
          - "Visual Studio 16 2019"
          - Ninja
        config:
          - Release

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      working-directory: build
      run: cmake -G "${{ matrix.generator }}" ..

    - name: Build with CMake
      working-directory: build
      run: cmake --build . --config ${{ matrix.config }}

    # Optionally, if you have tests set up:
    #- name: Run Tests
    #  working-directory: build
    #  run: ctest -C ${{ matrix.config }}
